제공된 인수로 함수를 호출하려고 시도하여 결과 또는 잡힌 오류 개체를 반환합니다.

-`try ... catch` 블록을 사용하여 함수 결과 또는 적절한 오류를 반환하십시오.
- 잡힌 객체가 'error'가 아닌 경우 새 '오류'를 만듭니다.